export const MILENIUM_INTERNAL_PHONE_ENV_KEYS = [
  'MILENIUM_DIRECTOR_PHONE',
  'MILENIUM_DEPARTMENT_PURCHASES_PHONE',
  'MILENIUM_DEPARTMENT_CONTROLLING_PHONE',
  'MILENIUM_DEPARTMENT_DP_PHONE',
  'MILENIUM_DEPARTMENT_FINANCE_PHONE',
  'MILENIUM_DEPARTMENT_MANAGEMENT_PHONE',
  'MILENIUM_DEPARTMENT_MAINTENANCE_PHONE',
  'MILENIUM_DEPARTMENT_MONITORING_PHONE',
  'MILENIUM_DEPARTMENT_OPERATIONAL_PHONE',
] as const;

export type MileniumInternalPhoneEnvKey =
  (typeof MILENIUM_INTERNAL_PHONE_ENV_KEYS)[number];
